### ISSUE TITLE
core: Re-run Substrate ECDSA tests on fail

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/canvas#211]
would it be possible to change the substrate test, so it re-runs the ECDSA test on failure (twice might be enough, but if it's easy to make it configurable, maybe up to N=3 times to start?)

**Comment by rjwebb** [comment]
I'm not sure if that would necessarily help because it would still result in a signer that fails ~1% of the time.

Another approach would be to change the signing method itself, so that it generates a nonce, signs the data with the nonce, then immediately tries to verify the signature. If verification fails, it generates a new nonce and tries again.

**Comment by rjwebb** [comment]
I've implemented a workaround here: https://github.com/canvasxyz/canvas/pull/212

**Comment by rjwebb** [comment]
resolved in #212

**Comment by raykyri** [comment]
nice!
