### ISSUE TITLE
GossipLog Hybrid Logical Clock - Clock Injectability

### ISSUE THREAD

**Issue by Chandelier-02** [canvasxyz/canvas#297]
Hi,

I have been using and testing GossipLog for a project I am working on. One idea that occurred to me is the limitation of only supporting vector clocks, which do not correlate to the actual passage of time. Being able to iterate over entries by time could be very useful.

I am not suggesting an overhaul of the vector clock implementation. Instead, I propose modularizing the clock and related message ID generation. This would allow users to implement their own clock and ID systems, provided the IDs remain lexicographically sortable.

The main challenge with this change is that the Message type is used extensively and would need to be updated, requiring significant refactoring. However, given that GossipLog is intended to be the backbone of a system, making it as modular and customizable as possible could be highly beneficial.

I am willing to explore this further but wanted to gather your thoughts before investing significant time into this.

Thank you!

**Comment by raykyri** [comment]
There are a lot of places in the log that depend on the vector clock functioning exactly as expected. One of them is that the Prolly tree assumes that vector clocks can be densely packed into the leading bytes of each record's key. It might be possible to explore a version that prefixes vector clocks with a timestamp -- you would have to do this anyway, since it's an invariant that actions increment the clock.
