### ISSUE TITLE
network explorer: incorrect message counts

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/canvas#331]
The message count gets out of sync when starting and stopping the server, when the server has a bootstrap address pointed at another node with messages on it. To replicate this, try e.g.

```
BOOTSTRAP_LIST=/dns4/network-explorer-libp2p.canvas.xyz/tcp/443/wss/p2p/12D3KooWJ5sLvhPM41HGurwM77PN1ugt7J2xQUNuVsM2dGgZfAwh npm run dev:server```

We should find a way to display message counts that doesn't have this problem (e.g. a sql count() query... if there aren't any reasons holding us back from that).

**Comment by rjwebb** [comment]
AFAIK the cause for this is that the `message` event can fire for the same message multiple times. For this reason I think we should make sure this event handler is idempotent for a given message id. One way to do this would be to get rid of the counts tables and use the database's built in count functionality to count actions, sessions and distinct addresses (which we only add once only because of the primary key constraints).

**Comment by raykyri** [comment]
Makes sense to me!
